### ISSUE TITLE
Extra Spaces

### ISSUE THREAD

**Issue by IM-TECHNO** [surjithctly/documentation-html-template#14]
There's a lot of spaces between one section and another as we didn't have so much text to put on. How to reduce it ?

**Comment by chamindujs** [comment]
@surjithctly Can I work on this issue?

**Comment by surjithctly** [comment]
Yes. go ahead

**Comment by IM-TECHNO** [comment]
Imma close this issue as I have fixed this myself ! It was long ago when I used this template for a Whatsapp BOT documentation. Now, the BOT is running well so is the website..
